<a href="https://colab.research.google.com/github/anamlf7/Notebook-5-y-7-Data-Science/blob/main/Copia_de_Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
import numpy as np
arr1=np.zeros(12)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
arr2=np.zeros(10)
arr2[4]=10
print(arr2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [4]:
arr3=np.arange(10,50)
print(arr3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
arr4=np.random.randint(0,8,(3,3))
print(arr4)

[[0 4 2]
 [4 3 4]
 [3 6 6]]


In [6]:
arr5=np.random.randint(0,300,100)
print(arr5)

[ 47 292  74 250 164 299  35 258 253 258 183   2 102 155 139 287 249  22
  62 189 199  33  57 153 173 289 148 254 137 180  84 154 269 114 284  77
 212 204 165 121 215 117 128 121 171 258 251 126 276 246 206 290 179 111
  14 110 142 268 273 141 211 222 169 196 224 119 255 147 253 297 212  28
 203 226 143 211   5  17 207 195 296 296  70 137  31  40 191 156  31  47
 241 192 174 248 247 134 162 142 113  32]


In [7]:
media=np.mean(arr5)
print(media)

167.9


In [8]:
np.var(arr5)

6836.430000000002

In [9]:
np.sum(arr5)/100

167.9

In [11]:
(np.sum((arr5 - media)**2))/len(arr5)

6836.430000000002

In [12]:
arr6= np.random.rand(5,5)
print(arr6)

[[0.70645158 0.71556738 0.36458818 0.18140162 0.65532087]
 [0.82887113 0.77001745 0.12288465 0.32732682 0.64645331]
 [0.23666326 0.31301432 0.33514549 0.02998498 0.56106709]
 [0.63541163 0.70265189 0.7829217  0.46738313 0.05298593]
 [0.31533065 0.2683734  0.34999454 0.16886182 0.02791927]]
